# ---------------------------------------------------- #
#           justTeams Configuration             #
# ---------------------------------------------------- #
# This file contains all the main settings for the plugin.
# For message customization, please see messages.yml.
# For GUI customization, please see gui.yml.
#
# You can use /team reload to apply changes without a server restart.
# ---------------------------------------------------- #

# CONFIG VERSION - DO NOT CHANGE THIS
config-version: 10

# ---------------------------------------------------- #
#                   Proxy Settings                     #
# ---------------------------------------------------- #
proxy_settings:
  # Set this to "VELOCITY", "BUNGEECORD", or "NONE".
  # This MUST match the proxy software you are using.
  # If this is wrong, cross-server teleports WILL NOT WORK.
  type: "VELOCITY"

# ---------------------------------------------------- #
#                  Storage Settings                    #
# ---------------------------------------------------- #
# Configure how the plugin stores its data.
storage:
  # Can be "mysql" for a central database or "h2" for local file-based storage.
  # H2 is recommended for single-server setups as it requires no configuration.
  # MySQL is required for multi-server networks (e.g., BungeeCord/Velocity) to sync data.
  type: "h2"

  # MySQL database settings.
  # Only used if type is "mysql" and enabled is "true".
  mysql:
    enabled: false
    host: "localhost"
    port: 3306
    database: "donutsmp"
    username: "root"
    password: ""

# ---------------------------------------------------- #
#                   General Settings                   #
# ---------------------------------------------------- #
settings:
  # Enable this to see detailed teleport and database logs in the console.
  # Useful for diagnosing cross-server issues.
  debug: false
  # This is a UNIQUE name for this specific server.
  # It is ABSOLUTELY CRUCIAL for cross-server features like /team home.
  # Each server in your network MUST have a different value here.
  # Good Examples: "survival-1", "factions-main", "skyblock", "lobby1", "lobby2"
  # Bad Example: Using "survival" on two different servers.
  server-identifier: "survival"
  # The main color used in GUIs and messages. Must be a hex code (e.g., "#4C9DDE").
  main_color: "#4C9DDE"
  # The accent color used for highlights and gradients.
  accent_color: "#4C96D2"
  # Maximum number of players allowed in a single team.
  max_team_size: 10
  # Minimum character length for a team name.
  min_name_length: 3
  # Maximum character length for a team name.
  max_name_length: 16
  # Maximum character length for a team tag.
  max_tag_length: 6
  # Maximum character length for a team description.
  max_description_length: 64
  # Default PvP status for newly created teams. If false, members cannot hurt each other by default.
  default_pvp_status: true

# ---------------------------------------------------- #
#                 Broadcast Settings                   #
# ---------------------------------------------------- #
broadcasts:
  # Set to true to announce server-wide when a new team is created.
  team-created: true
  # Set to true to announce server-wide when a team is disbanded by its owner.
  team-disbanded: true

# ---------------------------------------------------- #
#                 Team Home Settings                   #
# ---------------------------------------------------- #
team_home:
  # Time in seconds a player must stand still before being teleported.
  # Set to 0 to disable the warmup.
  warmup_seconds: 5
  # Cooldown in seconds before a player can use /team home again.
  # Players with the 'justteams.bypass.home.cooldown' permission ignore this.
  cooldown_seconds: 300 # 5 minutes

# ---------------------------------------------------- #
#                  Team Bank Settings                  #
# ---------------------------------------------------- #
# Requires Vault and an economy plugin (e.g., EssentialsX) to be installed.
team_bank:
  # Set to false to completely disable the team bank feature.
  enabled: true
  # Maximum balance a team bank can hold. Set to -1 for unlimited.
  max_balance: 1000000.0

# ---------------------------------------------------- #
#              Team Ender Chest Settings               #
# ---------------------------------------------------- #
team_enderchest:
  # Set to false to completely disable the team ender chest feature.
  enabled: true
  # Number of rows in the team ender chest. Must be between 1 and 6.
  rows: 3 # 3 rows = 27 slots

# ---------------------------------------------------- #
#              Visual and Sound Effects                #
# ---------------------------------------------------- #
effects:
  sounds:
    enabled: true
    # Sound played for successful actions (e.g., creating a team, depositing money).
    # A list of valid sound names can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    success: "ENTITY_PLAYER_LEVELUP"
    # Sound played for failed actions or errors.
    error: "ENTITY_VILLAGER_NO"
    # Sound played on teleportation.
    teleport: "ENTITY_ENDERMAN_TELEPORT"
  particles:
    enabled: true
    # Particle effect shown during teleport warmup.
    # A list of valid particle names can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
    teleport_warmup: "PORTAL"
    # Particle effect shown upon successful teleportation.
    teleport_success: "END_ROD"

# ---------------------------------------------------- #
#                   Webhook Settings                   #
# ---------------------------------------------------- #
# This feature sends anonymous startup statistics to the developer to help improve the plugin.
# It helps track usage and prioritize updates. No player or server IP data is ever sent.
# You can disable it at any time.
webhook:
  enabled: true
  # You can optionally set a server name to distinguish it in the statistics.
  server-name: "ServerName"