# ----------------------------------------------------
#  BetterDonutTeams Configuration
# ----------------------------------------------------
#  This file contains all the main settings for the plugin.
#  For message customization, please see messages.yml.
#
#  CONFIG VERSION - DO NOT CHANGE THIS
config-version: 5
# ----------------------------------------------------

# Storage settings
# Configure how the plugin stores its data.
storage:
  # Can be "mysql" for a central database or "h2" for local file-based storage.
  # H2 is recommended for smaller servers as it requires no setup.
  type: "h2"

  # MySQL database settings.
  # Only used if type is "mysql" and enabled is "true".
  mysql:
    enabled: false
    host: "localhost"
    port: 3306
    database: "donutsmp"
    username: "root"
    password: ""

# General team settings
settings:
  # The main color used in GUIs and messages.
  main_color: "#4C9DDE"
  # The accent color used for highlights.
  accent_color: "#4C96D2"
  # Maximum number of players allowed in a single team.
  max_team_size: 10
  # Minimum character length for a team name.
  min_name_length: 3
  # Maximum character length for a team name.
  max_name_length: 16
  # Maximum character length for a team tag.
  max_tag_length: 6
  # Maximum character length for a team description.
  max_description_length: 64
  # Default PvP status for newly created teams. If true, members can hurt each other.
  default_pvp_status: true

# Team Home feature settings
team_home:
  # Time in seconds a player must stand still before being teleported.
  # Set to 0 to disable the warmup.
  warmup_seconds: 5
  # Cooldown in seconds before a player can use /team home again.
  cooldown_seconds: 300 # 5 minutes

# Team Bank feature settings
team_bank:
  # Maximum balance a team bank can hold. Set to -1 for unlimited.
  max_balance: 1000000.0

# Team Ender Chest feature settings
team_enderchest:
  # Number of rows in the team ender chest. Must be between 1 and 6.
  rows: 3 # 3 rows = 27 slots

# Visual and sound effects
effects:
  sounds:
    enabled: true
    # Sound played for successful actions (e.g., creating a team, depositing money).
    # A list of sounds can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    success: "ENTITY_PLAYER_LEVELUP"
    # Sound played for failed actions or errors.
    error: "ENTITY_VILLAGER_NO"
    # Sound played on teleportation.
    teleport: "ENTITY_ENDERMAN_TELEPORT"
  particles:
    enabled: true
    # Particle effect shown during teleport warmup.
    # A list of particles can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
    teleport_warmup: "PORTAL"
    # Particle effect shown upon successful teleportation.
    teleport_success: "END_ROD"

# Webhook settings
# This feature sends anonymous startup statistics to the developer to help improve the plugin.
# You can disable it at any time.
webhook:
  enabled: true
  # You can optionally set a server name to distinguish it in the statistics.
  server-name: "ServerName"