name: DonutTeams
version: '${project.version}'
main: eu.kotori.donutTeams.DonutTeams
api-version: '1.21'
authors: [ kotori ]
description: A powerful teams plugin replica for DonutSMP.
commands:
  team:
    description: Main command for DonutTeams.
    usage: /<command> [subcommand]
    aliases: [t, clan, party]
  teammsg:
    description: Sends a message to your team.
    usage: /<command> <message>
    aliases: [tm, tmsg]