name: BetterDonutTeams
version: '${project.version}'
main: eu.kotori.donutTeams.DonutTeams
api-version: '1.21'
folia-supported: true
authors: [ kotori ]
description: A powerful teams plugin replica for DonutSMP, now with Folia support and more features.
softdepend: [ Vault, PlaceholderAPI, PvPManager ]

commands:
  team:
    description: Main command for BetterDonutTeams.
    usage: /<command> [subcommand]
    aliases: [t]
  guild:
    description: Main command for BetterDonutTeams.
    usage: /<command> [subcommand]
    aliases: [g]
  clan:
    description: Main command for BetterDonutTeams.
    usage: /<command> [subcommand]
    aliases: [c]
  party:
    description: Main command for BetterDonutTeams.
    usage: /<command> [subcommand]
    aliases: [p]
  teammsg:
    description: Sends a message to your team.
    usage: /<command> <message>
    aliases: [tm, tmsg]
  guildmsg:
    description: Sends a message to your team.
    usage: /<command> <message>
    aliases: [gmsg]
  clanmsg:
    description: Sends a message to your team.
    usage: /<command> <message>
    aliases: [cmsg]
  partymsg:
    description: Sends a message to your team.
    usage: /<command> <message>
    aliases: [pmsg]

permissions:
  donutteams.*:
    description: Grants all permissions for the plugin.
    children:
      - donutteams.admin
      - donutteams.user
  donutteams.admin:
    description: Grants access to all admin commands and bypasses.
    children:
      - donutteams.command.reload
      - donutteams.command.admin
      - donutteams.bank.withdraw.bypass
      - donutteams.enderchest.bypass
  donutteams.user:
    description: Grants access to all standard player commands.
    children:
      - donutteams.command.create
      - donutteams.command.disband
      - donutteams.command.invite
      - donutteams.command.accept
      - donutteams.command.deny
      - donutteams.command.leave
      - donutteams.command.kick
      - donutteams.command.info
      - donutteams.command.chat
      - donutteams.command.sethome
      - donutteams.command.home
      - donutteams.command.settag
      - donutteams.command.setdescription
      - donutteams.command.transfer
      - donutteams.command.promote
      - donutteams.command.demote
      - donutteams.command.pvp
      - donutteams.command.bank
      - donutteams.command.enderchest
      - donutteams.command.top
      - donutteams.command.teammsg
  donutteams.bank.withdraw.bypass:
    description: Allows bypassing team-specific withdrawal permissions.
    default: op
  donutteams.enderchest.bypass:
    description: Allows bypassing team-specific ender chest permissions.
    default: op
  donutteams.command.admin:
    description: Allows access to the /team admin command and GUI.
    default: op
  donutteams.command.create:
    description: Allows creating a team.
    default: true
  donutteams.command.disband:
    description: Allows disbanding a team.
    default: true
  donutteams.command.invite:
    description: Allows inviting players to a team.
    default: true
  donutteams.command.accept:
    description: Allows accepting a team invite.
    default: true
  donutteams.command.deny:
    description: Allows denying a team invite.
    default: true
  donutteams.command.leave:
    description: Allows leaving a team.
    default: true
  donutteams.command.kick:
    description: Allows kicking members from a team.
    default: true
  donutteams.command.info:
    description: Allows viewing team information.
    default: true
  donutteams.command.chat:
    description: Allows toggling team chat.
    default: true
  donutteams.command.sethome:
    description: Allows setting the team home.
    default: true
  donutteams.command.home:
    description: Allows teleporting to the team home.
    default: true
  donutteams.command.settag:
    description: Allows changing the team tag.
    default: true
  donutteams.command.setdescription:
    description: Allows changing the team description.
    default: true
  donutteams.command.transfer:
    description: Allows transferring team ownership.
    default: true
  donutteams.command.promote:
    description: Allows promoting a team member.
    default: true
  donutteams.command.demote:
    description: Allows demoting a team member.
    default: true
  donutteams.command.pvp:
    description: Allows toggling team PvP.
    default: true
  donutteams.command.bank:
    description: Allows using the team bank.
    default: true
  donutteams.command.enderchest:
    description: Allows using the team ender chest.
    default: true
  donutteams.command.top:
    description: Allows viewing the team leaderboards.
    default: true
  donutteams.command.teammsg:
    description: Allows sending a message to the team chat.
    default: true
  donutteams.command.reload:
    description: Allows reloading the plugin configuration.
    default: op